"""Initial Migration

Revision ID: 24b4ade3b07a
Revises: 
Create Date: 2026-05-19 11:18:23.415138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b4ade3b07a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_posto', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo_combustivel', sa.Enum('GASOLINA', 'DIESEL', 'ETANOL', name='tipocombustivel'), nullable=False),
    sa.Column('preco_por_litro', sa.Numeric(scale=2), nullable=False),
    sa.Column('volume_abastecido', sa.Numeric(scale=3), nullable=False),
    sa.Column('cpf_motorista', sa.String(), nullable=False),
    sa.Column('improper_data', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abastecimento')
    # ### end Alembic commands ###
